version: '3.8'

services:
  db:
    container_name: pg-docker
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "${DOCKER_DB_PORT}:5432"

  provider:
    build: .
    container_name: provider-api
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ENGINE: ${ENGINE}
      DJANGO_SETTINGS_MODULE: config.settings.development
      PROD_URI: "provider"
    depends_on:
      - db
  dashboard:
    build: 
      context: ./dashboard_app
    container_name: dashboard
    entrypoint: python main.py
    environment:
      XCLIENT__NAME: "Hotel Provider"
      XCLIENT__BASE_URL: "http://provider:8000"
      HOST: "0.0.0.0"
    ports:
      - "5000:5000"
    depends_on:
      - provider
