# Generated by Django 4.2.4 on 2023-08-11 06:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_lifecycle.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "id",
                    django_extensions.db.fields.RandomCharField(
                        blank=True,
                        editable=False,
                        length=40,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("capacity", models.IntegerField()),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("double", "Double"),
                            ("suite", "Suite"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("free", "Free"), ("occupied", "Occupied")],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("room_number", models.IntegerField()),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hotels.hotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "ordering": ["created"],
            },
            bases=(models.Model, django_lifecycle.mixins.LifecycleModelMixin),
        ),
        migrations.CreateModel(
            name="RoomAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "cit",
                    models.TimeField(
                        default=datetime.time(14, 0), verbose_name="Check In Time"
                    ),
                ),
                (
                    "cot",
                    models.TimeField(
                        default=datetime.time(12, 0), verbose_name="Check Out Time"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Availability",
                "verbose_name_plural": "Room Availabilities",
                "ordering": ["start_date"],
            },
            bases=(models.Model, django_lifecycle.mixins.LifecycleModelMixin),
        ),
    ]
