# Generated by Django 4.2.4 on 2023-08-11 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_alter_bookingevent_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingevent",
            options={"ordering": ["-timestamp"]},
        ),
    ]
