# Generated by Django 4.2.4 on 2023-08-11 06:56

from django.db import migrations, models
import django_lifecycle.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("website", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, django_lifecycle.mixins.LifecycleModelMixin),
        ),
    ]
